services:
  postgres:
    image: postgres:16
    container_name: rpg_postgres
    environment:
      POSTGRES_USER: rpg_admin
      POSTGRES_PASSWORD: rpg_admin_password
      POSTGRES_DB: rpg_game_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d 
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: rpg_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: rpg_game_db_mysql 
      MYSQL_USER: rpg_admin 
      MYSQL_PASSWORD: rpg_admin_password 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
    restart: unless-stopped

  mongo:
    image: mongo:latest  
    container_name: mongodb_steam
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password

  mongo-express:
    image: mongo-express
    container_name: mongo_express_steam
    restart: always
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_password
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  postgres_data:
  mysql_data:
  mongo_data: